import {StyleSheet} from 'react-native';
import * as COLOR from './constants';

const styles = StyleSheet.create({
	logo: {
		width: 200,
		height: 57.99,
		alignSelf: 'center',
		marginVertical: 10,
	},
	container: {
		paddingVertical: 15,
		paddingHorizontal: 5,
		flex: 1,
	},
	heading: {
		textAlign: 'center',
		fontWeight: 'bold',
		color: COLOR.primary_color,
		fontSize: 15,
		paddingTop: 25,
		paddingBottom: 0,
		textDecorationLine: 'underline'
	},
	form: {
		borderWidth: 1,
		borderRadius: 5,
		borderColor: COLOR.primary_color,
		paddingHorizontal: '1%',
	},
	grid:{
		flex: 0,
		flexDirection: 'row',
		flexWrap: 'wrap',
		alignItems: 'flex-start',
		paddingTop: 5
	},
	grid2:{
		flex: 0,
		flexDirection: 'row',
		flexWrap: 'wrap',
		alignItems: 'center',
		paddingVertical: 5,
		alignContent: 'center',
		justifyContent: 'center',
	},
	label: {
		textAlign: 'left',
		color: COLOR.extra_color2,
		fontSize: 13,
		paddingTop: 5,
		width: '57%',
	},
	sub_label: {
		textAlign: 'left',
		color: COLOR.extra_color2,
		fontSize: 13,
		fontWeight: 'bold',
		paddingTop: 5,
		width: '57%',
	},
	input_label: {
		textAlign: 'center',
		color: COLOR.extra_color2,
		fontSize: 13,
		fontWeight: 'bold',
		paddingTop: 5,
		width: '20%',
	},
	input: {
		textAlign: 'center',
		fontWeight: 'bold',
		color: COLOR.extra_color0,
		fontSize: 15,
		padding: 0,
		width: '20%',
		marginLeft: '1%',
		backgroundColor: COLOR.extra_color1,
		borderBottomWidth: 1,
		borderBottomColor: COLOR.extra_color0
	},
	input2: {
		textAlign: 'center',
		fontWeight: 'bold',
		color: COLOR.extra_color0,
		fontSize: 15,
		padding: 0,
		width: '35%',
		marginLeft: '1%',
		backgroundColor: COLOR.extra_color1,
		borderBottomWidth: 1,
		borderBottomColor: COLOR.extra_color0
	},
	sub_result: {
		textAlign: 'center',
		fontWeight: 'bold',
		color: COLOR.white,
		fontSize: 15,
		paddingHorizontal: 0,
		paddingVertical: 3,
		width: '20%',
		marginLeft: '1%',
		backgroundColor: COLOR.extra_color5,
		borderWidth: 1,
		borderColor: COLOR.extra_color0
	},
	result_col1: {
		textAlign: 'left',
		color: COLOR.extra_color2,
		fontSize: 13,
		fontWeight: 'bold',
		paddingTop: 5,
		width: '46%',
	},
	result_col11: {
		textAlign: 'left',
		color: COLOR.extra_color2,
		fontSize: 13,
		paddingTop: 5,
		width: '46%',
	},
	result_col2: {
		textAlign: 'center',
		color: COLOR.white,
		fontSize: 13,
		fontWeight: 'bold',
		borderWidth: 1,
		backgroundColor: COLOR.extra_color5,
		borderColor: COLOR.extra_color5,
		paddingTop: 5,
		width: '24%',
		paddingLeft: 5,
		marginLeft: '2%',
	},
	result_col21: {
		textAlign: 'center',
		color: COLOR.white,
		fontSize: 13,
		fontWeight: 'bold',
		borderWidth: 1,
		backgroundColor: COLOR.extra_color5,
		borderColor: COLOR.extra_color5,
		paddingTop: 5,
		width: '24%',
		paddingLeft: 5,
		marginLeft: '2%',
	},
});

export default styles;
